#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          wsnservice
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start wsnservice
### END INIT INFO
 
 
# Defaults
RUN_MODE="daemons"
 
JAVA=/usr/bin/java
DAEMONDIR=/path/to/WSN-Service-Base
DAEMON=build/jar/WSN-Linux.jar
PIDDIR=/var/run
WSNSERVICEPID=$PIDDIR/wsnservice.pid
DAEMONARGS="build/jar/dtn.config.xml 3 build/wsnservice.log"
 
. /lib/lsb/init-functions
 
case "$1" in
	start)
		pidofproc -p $WSNSERVICEPID $JAVA >/dev/null
                status=$?
                if [ $status -eq 0 ]; then
                        log_success_msg "wsnservice is already running"
                else
                        log_failure_msg "Starting wsnservice"
                	log_progress_msg "wsnservice"
               		# Make sure we have our PIDDIR, even if it's on a tmpfs
                	install -o root -g root -m 755 -d $PIDDIR
                	if ! start-stop-daemon --start --chdir $DAEMONDIR --pidfile $WSNSERVICEPID --make-pidfile --background --exec $JAVA -- -jar $DAEMON $DAEMONARGS ; then
                    		log_end_msg 1
                    		exit 1
                	fi
                	log_end_msg 0
                fi
		;;
	stop)
		pidofproc -p $WSNSERVICEPID $JAVA >/dev/null
                status=$?
		if [ $status -eq 0 ]; then
                	log_daemon_msg "Stopping wsnservice"
                	log_progress_msg "wsnservice"

                	start-stop-daemon --stop --quiet --pidfile $WSNSERVICEPID
                	# Wait a little and remove stale PID file
                	sleep 1
                	if [ -f $WSNSERVICEPID ] && ! ps h `cat $WSNSERVICEPID` > /dev/null
                		then
                        	# Stale PID file (wsnservice was succesfully stopped),
                        	# remove it
                        	rm -f $WSNSERVICEPID
                	fi

                	log_end_msg 0
		else
                        log_failure_msg "wsn service is not running"
                fi

		;;
	restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		pidofproc -p $WSNSERVICEPID $JAVA >/dev/null
		status=$?
		if [ $status -eq 0 ]; then
			log_success_msg "wsnservice is running"
		else
			log_failure_msg "wsnservice is not running"
		fi
		exit $status
		;;
	*)
		echo "Usage: /etc/init.d/wsnservice {start|stop|restart|force-reload|status}"
		exit 1
		;;
esac
 
exit 0
